name: .NET Unit Tests

on:
  push:
    branches:
      - master
      - ci/cd
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests with coverage
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="./coverage/" --test-adapter-path:. --logger:"junit;LogFilePath=./coverage/test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/**/coverage.cobertura.xml
