name: .NET Unit Tests

on:
  push:
    branches:
      - master
      - ci/cd
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

#      - name: Run tests with coverage
#        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura,opencover" /p:CoverletOutput="./coverage/coverage"

      - name: Dotnet Test Coverlet
        uses: alsi-lawr/dotnet-test-coverlet@v1
        with:
          dotnet-version: 8.0
        
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/**/coverage.cobertura.xml
